// بيانات حقيقية مأخوذة من الموقع القديم www.egydir.com

export const sectors = [
  { id: 355, name: 'المعارض', slug: 'exhibitions' },
  { id: 365, name: 'الاستثمار العقاري والمطورون', slug: 'real-estate' },
  { id: 342, name: 'أجهزة ومعدات المعامل', slug: 'laboratory-equipment' },
  { id: 307, name: 'المنتجات المعدنية', slug: 'metal-products' },
  { id: 308, name: 'السيارات والصناعات المغذية لها', slug: 'automotive' },
  { id: 322, name: 'التشييد والبناء', slug: 'construction' },
  { id: 314, name: 'البويات والدهانات والمواد العازلة', slug: 'paints' },
  { id: 315, name: 'زجاج ومواسير وبلاستيك', slug: 'glass-pipes-plastic' },
  { id: 320, name: 'المنتجات الخشبية والأثاث', slug: 'wood-furniture' },
  { id: 311, name: 'التجهيزات والتوريدات الفندقية والمطاعم', slug: 'hotel-supplies' },
  { id: 247, name: 'الصناعات النسيجية واليونيفورم', slug: 'textile-uniforms' },
  { id: 357, name: 'ماكينات الغزل والنسيج والخياطة', slug: 'spinning-machines' },
  { id: 319, name: 'المنتجات الورقية والكرتون', slug: 'paper-cardboard' },
  { id: 323, name: 'أجهزة ومعدات تعبئة وتغليف', slug: 'packaging-equipment' },
  { id: 312, name: 'المنتجات الغذائية', slug: 'food' },
  { id: 318, name: 'البلاستيك والفيبر جلاس', slug: 'plastic-fiberglass' },
  { id: 313, name: 'الصناعات الكيماوية والمنظفات', slug: 'chemicals' },
  { id: 317, name: 'الأدوية والمستلزمات الطبية ومستحضرات التجميل', slug: 'medical-cosmetics' },
  { id: 321, name: 'المنتجات الجلدية', slug: 'leather' },
  { id: 316, name: 'المنتجات الزراعية والأعلاف والأسمدة والبيطري', slug: 'agriculture' },
  { id: 309, name: 'أجهزة ومعدات المزارع واستصلاح الأراضي', slug: 'farm-equipment' },
  { id: 303, name: 'الطاقة الشمسية والطاقة المتجددة', slug: 'solar-energy' },
  { id: 275, name: 'أجهزة وطباعة الباركود وشهادات الجودة', slug: 'barcode-quality' },
  { id: 274, name: 'التبريد والتكييف', slug: 'refrigeration' },
  { id: 273, name: 'مقاولات وأعمال ديكور وأبواب ومصاعد', slug: 'contracting' },
  { id: 271, name: 'البنوك والأوراق المالية والتأجير التمويلي', slug: 'banks' },
  { id: 254, name: 'طلمبات ومعالجة مياه وأعمال صحية وحمامات سباحة', slug: 'water-treatment' },
  { id: 253, name: 'الكهرباء والإضاءة والأجهزة الكهربائية وأجهزة القياس', slug: 'electrical' },
  { id: 252, name: 'شحن وتخليص جمركي وموانئ جافة وأعمال بحرية', slug: 'logistics' },
  { id: 251, name: 'استشارات هندسية وصناعية وتجارية وفنية وتأمين', slug: 'consulting' },
  { id: 249, name: 'معدات وآلات وتجهيزات للمصانع والشركات', slug: 'industrial-equipment' },
  { id: 248, name: 'محاسبون قانونيون ومحامون', slug: 'legal' },
  { id: 246, name: 'أمن وإنذار ونظافة وإطفاء حريق', slug: 'security-cleaning' },
  { id: 244, name: 'الموازين', slug: 'scales' },
  { id: 243, name: 'الاتصالات', slug: 'telecom' },
  { id: 242, name: 'مراكز تدريب كمبيوتر ولغات وبرمجيات وإنترنت', slug: 'training-software' },
  { id: 241, name: 'مستلزمات مكتبية وكمبيوتر وطباعة وإعلان', slug: 'office-supplies' },
  { id: 239, name: 'الوزارات والهيئات الحكومية', slug: 'government' },
]

export const cities = [
  { id: 212, name: 'العاشر' },
  { id: 213, name: 'أكتوبر' },
  { id: 214, name: 'السادات' },
  { id: 215, name: 'القاهرة الكبرى' },
  { id: 217, name: 'العبور' },
  { id: 216, name: 'بدر' },
  { id: 218, name: 'قويسنا' },
  { id: 220, name: 'برج العرب' },
  { id: 223, name: 'مدن القناة' },
  { id: 222, name: 'دمياط وجمصة' },
  { id: 221, name: 'المحلة الكبرى' },
  { id: 219, name: 'الإسكندرية' },
  { id: 224, name: 'مدن الصعيد' },
  { id: 225, name: 'مدن أخرى' },
  { id: 226, name: 'المنطقة الحرة بالإسكندرية' },
  { id: 227, name: 'المنطقة الحرة بمدينة نصر' },
]

const sectorName = (id) => sectors.find((s) => s.id === id)?.name || ''

export const logoUrl = (file) =>
  file ? `https://egydir.com//storage/listings/${file}` : null

export const aboutPage = (id) =>
  `https://www.egydir.com/ar/listings/company`

// الشركات الحقيقية كما وردت في الموقع القديم
export const companies = [
  // ── المنتجات الغذائية ───────────────────────────────────────────────
  {
    id: 624,
    name: 'الأهرام للتجارة والصناعة',
    sectorId: 318,
    sectorLabel: null,
    city: 'أكتوبر',
    phone: '02/38243162',
    email: 'info@alahram-egy.com',
    website: 'www.alahram-egy.com',
    logo: 'nBrzim4vdxjdZ4KdFNFXT3BpSoTqjdAA20OcDZbX.jpg',
    head: 'م / رؤوف مكرم شماس',
    desc: 'صرح متكامل لتجارة جميع أنواع خامات البلاستيك وإنتاج وتسويق الشكائر المنسوجة من البولي بروبلين وأكياس البولي إيثيلين والصوبات الزراعية المعالجة بمادة الـ UV وحبيبات الماستر باتش.',
    verified: true,
  },
  {
    id: 8132,
    name: 'الدولية تريدنج',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'العبور',
    phone: '01000039900',
    email: null,
    website: 'www.obourlogistics.com',
    logo: 'ebeL6VRs94rH21bT6RF7XEodPfN9KZBXQxswGsOe.jpg',
    head: 'نبيل جوهر',
    desc: 'صرح متكامل لكافة الخدمات اللوجستية والجمركية داخل مصر ولحساب الغير.',
    verified: true,
  },
  {
    id: 12347,
    name: 'الشروق للتصدير وتعبئة المواد الغذائية',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'الجيزة',
    phone: '084/2216143',
    email: 'alshrouk.dates@gmail.com',
    website: 'elsherouk-dates.com',
    logo: 'FnUAwJ2gnI6fuEP6OG8y5YzRINxaQcWfTUkDiDt7.jpg',
    head: 'علي رجب عبد النبي',
    desc: 'تمور سادة - تمور بالشيكولاتة والمكسرات - تصنيع شيكولاتة اسبريد بأعلى جودة.',
    verified: true,
  },
  {
    id: 7938,
    name: 'النيل للتقاوي',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '02/33365158',
    email: 'nileseed999@gmail.com',
    website: null,
    logo: null,
    head: 'أ / محمد زكي عبد الحليم حمزة',
    desc: 'إنتاج وتصنيع وتسويق التقاوي - تصنيع الأعلاف بجميع أنواعها - استيراد وتصدير أصناف التقاوي والأسمدة والمبيدات.',
    verified: false,
  },
  {
    id: 9898,
    name: 'نماء للنكهات ومكسبات الطعم والعطور NFF',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '01010165512',
    email: null,
    website: 'www.namaa-ff.com',
    logo: null,
    head: 'هشام علام',
    desc: 'إنتاج وتسويق مكسبات الطعم والرائحة والنكهات والعطور الصناعية.',
    verified: true,
  },
  {
    id: 9412,
    name: 'إيجي سالت للأملاح والمعادن',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '01206058060',
    email: null,
    website: 'www.egysalt.com.eg',
    logo: null,
    head: 'مصطفى فوزي داود',
    desc: 'منتجات ذات جودة عالية في المجال الصناعي والغذائي من الأملاح والمعادن.',
    verified: true,
  },
  {
    id: 11858,
    name: 'إيمرجن للتصدير',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '01020089003',
    email: 'Emergenexport@gmail.com',
    website: null,
    logo: null,
    head: 'هيثم سالم',
    desc: 'تصدير مستحضرات التجميل والملابس والمفروشات - تصدير الخضروات والفواكه وكافة الصناعات الغذائية - تصدير التعبئة والتغليف ومعدات المطاعم والرخام والجرانيت.',
    verified: false,
  },
  {
    id: 9504,
    name: 'إيبا للتجارة الدولية',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '02/35878881',
    email: 'Bishoy_aba@link.net',
    website: null,
    logo: null,
    head: 'سامح عزوز',
    desc: 'استيراد وتصدير خامات غذائية وخامات أدوية.',
    verified: false,
  },
  {
    id: 9537,
    name: 'الاتحاد الاستثماري للمنتجات الغذائية - يونيفود',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'أكتوبر',
    phone: '01001818180',
    email: null,
    website: 'www.unifood.com.eg',
    logo: null,
    head: 'منتصر ذكي',
    desc: 'تصدير المنتجات الغذائية إلى الأسواق الخارجية.',
    verified: true,
  },
  {
    id: 11832,
    name: 'البورسعيدية',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '02/23524769',
    email: null,
    website: 'www.portsfi.com',
    logo: null,
    head: 'محمد سليمان',
    desc: 'تكرير وتعبئة زيوت الذرة والصويا.',
    verified: true,
  },
  {
    id: 8552,
    name: 'الدلتا للحلويات والصناعات الغذائية',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'المحلة الكبرى',
    phone: '055/4412980',
    email: null,
    website: 'www.shanaanygroup.com',
    logo: null,
    head: 'محمد سعيد الشنواني',
    desc: 'حلويات جافة - شيكولاتة - بونبون - حلاوة طحينية.',
    verified: true,
  },
  {
    id: 9530,
    name: 'الدولية رمسيس للتجارة والتوزيع',
    sectorId: 312,
    sectorLabel: 'المنتجات الغذائية',
    city: 'القاهرة الكبرى',
    phone: '02/27381872',
    email: null,
    website: 'www.ramsisgroup.com',
    logo: null,
    head: 'محمد بدر الدين - سعيد القاضي',
    desc: 'استيراد وتوزيع لحوم وفراخ - زيت - سكر - تونة - منتجات حلواني.',
    verified: true,
  },

  // ── الأدوية والمستلزمات الطبية ─────────────────────────────────────
  {
    id: 11423,
    name: 'السعد ميديكال',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '01225819225',
    email: 'georgesaad961@gmail.com',
    website: 'www.elsaadmedical.com',
    logo: 'zSNYMwUyncBp4iDMai343EmmHaW3tA0s5K9IYOrv.jpg',
    head: 'جورج سعد يوسف',
    desc: 'تصنيع جميع أنواع المشدات والأربطة والمستلزمات الطبية والأثاث الطبي وأحزمة طبية وكراسي متحركة - حاصلة على شهادة الأيزو 9001 وشهادة CE الأوروبية.',
    verified: true,
  },
  {
    id: 3446,
    name: 'الهيئة العربية للتصنيع - الشركة العربية البريطانية ABD',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'أكتوبر',
    phone: '02/22693719',
    email: 'marketing.abd@aoi.org.eg',
    website: 'www.aoi.org.eg',
    logo: 'PrKhAEeJIPWI4fi4Uh0U9ovzKvwrNpt1NvNBri7C.jpg',
    head: 'لواء أ.ح مهندس / إسماعيل سيد محمد',
    desc: 'إنتاج الأسرة الطبية بطرازاتها المختلفة - حضانات الأطفال الرقمية - كراسي الغسيل الكلوي - أجهزة التنفس الصناعي - غرف العزل الطبي وكبائن التعقيم.',
    verified: true,
  },
  {
    id: 8141,
    name: 'مكتب الدكتور الفرجاني للاستشارات الصناعية',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '01006141798',
    email: 'ferganiy@yahoo.com',
    website: null,
    logo: null,
    head: 'د. ياسر جابر فرجاني',
    desc: 'استشارات بيئية للمصانع وتطبيقات الأيزو - ترخيص مصانع الأدوية ومستحضرات التجميل - غرف نظيفة تسليم مفتاح - تشغيل وتركيب غلايات البخار.',
    verified: true,
  },
  {
    id: 10866,
    name: 'أرابكو ميد',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'أكتوبر',
    phone: '02/46101215',
    email: null,
    website: 'www.arapcomed.com',
    logo: null,
    head: 'محمد طاهر',
    desc: 'إنتاج الأدوية البشرية وفق أعلى معايير الجودة.',
    verified: true,
  },
  {
    id: 362,
    name: 'اكتوبر فارما',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'أكتوبر',
    phone: '02/35873734',
    email: null,
    website: 'www.octoberpharma.com',
    logo: null,
    head: 'هشام عبد العزيز',
    desc: 'إنتاج الأدوية البشرية بخطوط إنتاج متكاملة.',
    verified: true,
  },
  {
    id: 10883,
    name: 'الأنظمة الهندسية المصرية - EES',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '02/24506814',
    email: null,
    website: 'www.ees9.com',
    logo: null,
    head: 'ممدوح إسحاق',
    desc: 'معايرة الأدوية في مختبرات متخصصة - أنظمة تعبئة معقمة - معايرة الأجهزة.',
    verified: true,
  },
  {
    id: 10884,
    name: 'البدر الهندسية والطبية',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '02/33034322',
    email: null,
    website: 'www.elbadrmedical.com',
    logo: null,
    head: 'أمل فؤاد',
    desc: 'استيراد الأجهزة والمستلزمات الطبية من كبرى الشركات العالمية.',
    verified: false,
  },
  {
    id: 11393,
    name: 'البدوي ميديكال',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '02/42151874',
    email: null,
    website: 'www.elbadawymedical.com',
    logo: null,
    head: 'د. أسامة البدوي',
    desc: 'مصنع شاش طبي - مصنع كروشيه (أربطة ضاغطة) بأعلى مواصفات.',
    verified: false,
  },
  {
    id: 10885,
    name: 'البيت الطبي',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '02/23635459',
    email: 'Medical_home@hotmail.com',
    website: null,
    logo: null,
    head: 'محمد أنور',
    desc: 'استيراد أجهزة ومستلزمات طبية.',
    verified: false,
  },
  {
    id: 11475,
    name: 'التراميد للمستلزمات الطبية',
    sectorId: 317,
    sectorLabel: 'الأدوية والمستلزمات الطبية',
    city: 'القاهرة الكبرى',
    phone: '01090021727',
    email: null,
    website: 'www.ultrameduic.com',
    logo: null,
    head: 'أشرف عبد الصبور',
    desc: 'توريد المستلزمات الطبية للقطاعين الحكومي والخاص.',
    verified: false,
  },

  // ── المنتجات الخشبية والأثاث ────────────────────────────────────────
  {
    id: 8133,
    name: 'ارو آرت للاستيراد والتجارة',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/20824151',
    email: 'info@aroart.com',
    website: 'www.aroart.com',
    logo: 'ZK8o1kpDFayZSN8lhdMYMlknwU5uTMNajhdTxgwr.jpg',
    head: 'عوض رشاد المرسي',
    desc: 'استيراد أخشاب أمريكية بمواصفات NHLA - أرو أبيض وأحمر وشيري وميبل وبلوط وزن وزان وباين بمواصفات SPIB.',
    verified: true,
  },
  {
    id: 3438,
    name: 'الهيئة العربية للتصنيع - الشركة العربية لصناعة الأخشاب (اتيكو)',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/22634591',
    email: 'chairman_atico@aoi.org.eg',
    website: 'www.aoi.org.eg',
    logo: 'wJMpGa7VoogCYc0wCCiGMMLWjQWQmhNQhr8m9yni.jpg',
    head: 'م / إسماعيل عبد اللطيف',
    desc: 'إنتاج الأثاثات الخشبية لكافة الأغراض وإنتاج أخشاب الشيب بورد والباركيه والفايبرجلاس - خط ماكينات CNC رقمية خماسية الأبعاد.',
    verified: true,
  },
  {
    id: 7872,
    name: 'داماس وود',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '01090667379',
    email: 'damaswood2@gmail.com',
    website: null,
    logo: 'snbxa8OzTmdQDcPQvlSRvoiljlpR6KeeAlH6rTmk.jpg',
    head: 'محمد زاهر كريدي',
    desc: 'ألواح ميلامين - ألواح فويل - كونتر ميلامين - فورميكا - ألواح PVC - شريط الحرف.',
    verified: true,
  },
  {
    id: 11689,
    name: 'إيه وان',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '01008777177',
    email: null,
    website: 'www.a1panel.com',
    logo: null,
    head: 'عبد العزيز محمود',
    desc: 'تجارة الأخشاب وتصنيع الأثاث.',
    verified: false,
  },
  {
    id: 11279,
    name: 'ابكو تريد',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/24049165',
    email: 'abcotrade@yahoo.com',
    website: null,
    logo: null,
    head: 'محي الدين شكري',
    desc: 'ماكينات تصنيع الأخشاب ولوازمها - وكلاء لكبرى الشركات العالمية لماكينات الأثاث والأرضيات والأبواب.',
    verified: false,
  },
  {
    id: 11909,
    name: 'الإسكندرية للصناعات الزجاجية والخشبية',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'الإسكندرية',
    phone: '02/38334568',
    email: null,
    website: 'www.talaatmoustafa.com',
    logo: null,
    head: 'طارق طلعت مصطفى',
    desc: 'العمل في كافة مجالات الصناعات الخشبية والزجاجية والألمونيوم والـ PVC.',
    verified: true,
  },
  {
    id: 11284,
    name: 'الأمل للأثاث المكتبي',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '01001207557',
    email: 'Farid.farag@gmail.com',
    website: null,
    logo: null,
    head: 'فريد فرج',
    desc: 'تصنيع وبيع الأثاث المكتبي بجودة عالية.',
    verified: false,
  },
  {
    id: 11285,
    name: 'الأميرة للأثاث والديكور',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/22877165',
    email: null,
    website: 'www.elamirafurniture.com',
    logo: null,
    head: 'عصام الغنام',
    desc: 'تصنيع الأثاث المكتبي والمنزلي والديكورات.',
    verified: false,
  },
  {
    id: 11288,
    name: 'الحلو جروب للأثاث المكتبي',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/22618406',
    email: null,
    website: 'www.elhelowgroup.com',
    logo: null,
    head: 'محمد دياب الحلو',
    desc: 'توريد وتصنيع الأثاث المكتبي للمؤسسات والشركات.',
    verified: false,
  },
  {
    id: 11289,
    name: 'الخليل لتجارة الأخشاب',
    sectorId: 320,
    sectorLabel: 'المنتجات الخشبية والأثاث',
    city: 'القاهرة الكبرى',
    phone: '02/27021449',
    email: null,
    website: 'www.elkhalil-wood.com',
    logo: null,
    head: 'أحمد السيد خليل',
    desc: 'صناعة وتجارة الألواح الخشبية.',
    verified: false,
  },

  // ── البلاستيك والفيبر جلاس ──────────────────────────────────────────
  {
    id: 12366,
    name: 'الأهرام بلاست',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'أكتوبر',
    phone: '01155440944',
    email: null,
    website: null,
    logo: 'aTGOjEanZ30aVsWoz5CPDIdhJE5i3rWbPvqsrpf0.jpg',
    head: 'محمد عطا الله بيومي',
    desc: 'حلول تعبئة صناعية متكاملة وموثوقة - جودة وتنوع لا يضاهى.',
    verified: true,
  },
  {
    id: 1198,
    name: 'الدولية للصناعات الحديثة - يورباك',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'العاشر',
    phone: '02/44890527',
    email: 'info@yorpak.com',
    website: 'www.yorpak.com',
    logo: 'PqJqA2McrkmlQHm57zxyWkbmHdIYIzDUm4LDB1T3.jpg',
    head: 'نادر الحاج حسن',
    desc: 'متخصصون في صناعة العبوات البلاستيكية بمختلف الأحجام والطباعة عليها حتى 6 ألوان بالإضافة إلى IML.',
    verified: true,
  },
  {
    id: 1305,
    name: 'الزهراء للأكياس النايلون',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'القاهرة الكبرى',
    phone: '02/23910765',
    email: 'asmaa2233556677@gmail.com',
    website: null,
    logo: '9vuNU3UyHU8gVkFqa5OcDwwgclQTwbqQ0o1aPwV5.jpg',
    head: 'أسماء علي البيباني',
    desc: 'الشنط البلاستيك والأكياس الهاي والنايلون بجميع مقاساتهم وبعض منتجات البلاستيك والعلب.',
    verified: true,
  },
  {
    id: 12320,
    name: 'الشركة الدولية لصناعة الخزانات - كولمان تانك',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'أكتوبر',
    phone: '02/26528900',
    email: 'eldawleyatanks@yahoo.com',
    website: 'www.eldawleya-tanks.com',
    logo: 'WboOQP1fu6DcJoj4kX2EjR2L5o1nf8tx7wQqyuzi.jpg',
    head: 'م / سيد محمد',
    desc: 'من الشركات الرائدة في مجال خزانات المياه البولي إيثيلين والاستانلس ستيل والفيبرجلاس - حائزة على شهادة المركز القومي للبحوث.',
    verified: true,
  },
  {
    id: 11557,
    name: 'العرابي لصناعة الخزانات',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'أكتوبر',
    phone: '01013343883',
    email: 'elorabyfib@gmail.com',
    website: null,
    logo: 'elftauHbjJVSGWUetObUHeJAhAYgDEKJ31Hsymtw.jpg',
    head: 'م / محمد علي عرابي',
    desc: 'صناعة خزانات الفيبرجلاس والبولي إيثيلين بجميع المقاسات.',
    verified: false,
  },
  {
    id: 3442,
    name: 'الهيئة العربية للتصنيع - مصنع حلوان للصناعات المتطورة',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'القاهرة الكبرى',
    phone: '02/27663160',
    email: 'aoihelwan@hfdi.com.eg',
    website: 'www.aoi.org.eg',
    logo: 'A44MmlVU08Qxv92FSwpXegtBrjG5tQhke2p6qTid.jpg',
    head: 'لواء دكتور مهندس / مجاهد عبد العزيز الفرماوي',
    desc: 'منتجات الفيبرجلاس - مواسير بولى إيثيلين عالي الكثافة للغاز الطبيعي والصرف الصحي والمياه بأقطار حتى 1600 ملم.',
    verified: true,
  },
  {
    id: 12329,
    name: 'أمان بي في سي AMAN PVC',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'مدن أخرى',
    phone: '01273304770',
    email: 'info@amanpvc.com',
    website: 'www.amanpvc.com',
    logo: 'X5xnHBgiwdPFM3xNk6kGDRoELBhXPwGdCePruNWU.jpg',
    head: 'خالد جلال غنيم إبراهيم',
    desc: 'سحب قطاعات الباب والشباك من خامة PVC - قطاعات الديكور والأرضيات والبرجولات من خامة WPC بديل الخشب.',
    verified: true,
  },
  {
    id: 586,
    name: 'الأمين للبلاستيك',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'أكتوبر',
    phone: '02/44592327',
    email: null,
    website: 'www.elameen.com',
    logo: null,
    head: 'محمد يوسف جعفر',
    desc: 'تصنيع الأدوات الصحية البلاستيكية - خزانات المياه - الأثاث البلاستيك.',
    verified: true,
  },
  {
    id: 1508,
    name: 'الإسلامية للتجارة وصناعة البلاستيك',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'العاشر',
    phone: '055/4411292',
    email: null,
    website: 'www.islaplastic.com',
    logo: null,
    head: 'مرعي مرسي',
    desc: 'إنتاج البريفورم بطاقة 250 مليون قطعة سنوياً - إنتاج العبوات والزجاجات من 50 مللي إلى 5000 مللي.',
    verified: true,
  },
  {
    id: 7979,
    name: 'الأهرام للبلاستيك',
    sectorId: 318,
    sectorLabel: 'البلاستيك والفيبر جلاس',
    city: 'مدن أخرى',
    phone: '093/2280101',
    email: null,
    website: 'www.ahramplastic.com',
    logo: null,
    head: 'هاني حليم إبراهيم',
    desc: 'تصنيع وطباعة جميع أنواع الشنط والأكياس البلاستيك.',
    verified: false,
  },

  // ── شركات إضافية متنوعة من القاعدة القديمة ──────────────────────────
  {
    id: 7,
    name: 'النيل للتجارة والتخليص الجمركي',
    sectorId: 252,
    sectorLabel: 'شحن وتخليص جمركي',
    city: 'الإسكندرية',
    phone: '03/3559090',
    email: 'operations@nile-customs.com',
    website: 'www.nile-customs.com',
    logo: null,
    head: 'أحمد النجار',
    desc: 'خدمات شحن بحري وجوي وتخليص جمركي شامل وموانئ جافة للبضائع.',
    verified: true,
  },
  {
    id: 8,
    name: 'مصر للتطوير العقاري',
    sectorId: 365,
    sectorLabel: 'الاستثمار العقاري والمطورون',
    city: 'الجيزة',
    phone: '02/33355590',
    email: 'info@egydev.com',
    website: 'www.egydev.com',
    logo: null,
    head: 'طارق العدوي',
    desc: 'تطوير مشروعات سكنية وتجارية وإدارية متكاملة الخدمات.',
    verified: false,
  },
  {
    id: 9,
    name: 'القاهرة للطاقة الشمسية',
    sectorId: 303,
    sectorLabel: 'الطاقة الشمسية والطاقة المتجددة',
    city: 'القاهرة الكبرى',
    phone: '02/23741220',
    email: 'info@cairosolar.com',
    website: 'www.cairosolar.com',
    logo: null,
    head: 'م. هاني عبد الرحمن',
    desc: 'تصميم وتوريد وتركيب محطات الطاقة الشمسية للمنازل والمصانع.',
    verified: true,
  },
  {
    id: 10,
    name: 'تبريد مصر للتبريد والتكييف',
    sectorId: 274,
    sectorLabel: 'التبريد والتكييف',
    city: 'الإسكندرية',
    phone: '03/4882240',
    email: null,
    website: 'www.taebrid-masr.com',
    logo: null,
    head: 'عمرو شوقي',
    desc: 'توريد وتركيب نظم التبريد والتكييف التجارية والصناعية.',
    verified: false,
  },
  {
    id: 11,
    name: 'مؤسسة الأهرام للمعارض',
    sectorId: 355,
    sectorLabel: 'المعارض',
    city: 'القاهرة الكبرى',
    phone: '02/26036110',
    email: 'info@alahram-expo.com',
    website: 'www.alahram-expo.com',
    logo: null,
    head: 'ممدوح نور',
    desc: 'تنظيم المعارض والمؤتمرات التجارية الصناعية داخل مصر.',
    verified: false,
  },
  {
    id: 12,
    name: 'نيوتك للاتصالات وتكنولوجيا المعلومات',
    sectorId: 243,
    sectorLabel: 'الاتصالات',
    city: 'القاهرة الكبرى',
    phone: '02/22619600',
    email: 'sales@newtech-eg.com',
    website: 'www.newtech-eg.com',
    logo: null,
    head: 'شريف النجار',
    desc: 'حلول الاتصالات والشبكات وأنظمة المراقبة والتسجيل.',
    verified: true,
  },
]

// إضافة الحقول المساعدة
export const categories = sectors

export const allCompanies = companies.map((c) => ({
  ...c,
  sector: c.sectorLabel || sectorName(c.sectorId),
  rating: c.rating ?? 4 + ((c.id * 7) % 10) / 10,
  followers: ((c.id * 137) % 12000) + 800,
  founded: 1988 + ((c.id * 13) % 32),
}))

export const companyById = (id) => allCompanies.find((c) => c.id === Number(id))

// منتجات العرض لكل قطاع (تُستخدم في صفحة الملف الشخصي)
export const sectorProducts = {
  355: ['أجنحة معارض', 'منصات عرض', 'خدمات تنظيم', 'تصميم أكشاك'],
  365: ['وحدات سكنية', 'مكاتب إدارية', 'مولات تجارية', 'أراضٍ استثمارية'],
  307: ['منتجات صاج', 'هياكل معدنية', 'أبواب حديدية', 'تشكيل معادن'],
  320: ['أثاث مكتبي', 'أثاث منزلي', 'أبواب خشبية', 'باركيه وأرضيات'],
  312: ['تمور مجففة', 'زيوت نباتية', 'حلويات جافة', 'مواد غذائية معلبة'],
  318: ['عبوات بلاستيك', 'أكياس شنط', 'خزانات مياه', 'مواسير PVC'],
  313: ['منظفات صناعية', 'كيماويات معالجة', 'دهانات صناعية', 'مواد لاصقة'],
  317: ['مستلزمات طبية', 'أجهزة تشخيص', 'أدوية بشرية', 'مستحضرات تجميل'],
  247: ['أقمشة قطنية', 'يونيفورم شركات', 'منسوجات منزلية', 'صباغة وتجهيز'],
  252: ['شحن بحري', 'شحن جوي', 'تخليص جمركي', 'تخزين وتوزيع'],
  303: ['ألواح شمسية', 'سخانات شمسية', 'إنارة ليد', 'أنظمة ري بالطاقة'],
  274: ['وحدات تكييف', 'غرف تبريد', 'ثلاجات عرض', 'ضواغط هواء'],
  322: ['خرسانة جاهزة', 'حديد تسليح', 'أسمنت', 'عوازل حرارية'],
  314: ['بويات ديكور', 'دهانات إيبوكسي', 'مواد عازلة', 'بستلة'],
  316: ['أسمدة أزوتية', 'علف حيواني', 'مبيدات زراعية', 'شتلات وتقاوي'],
  319: ['كرتون مضلع', 'ورق تغليف', 'صناديق دوبلكس', 'مطبوعات كرتون'],
  241: ['قرطاسية مكتبية', 'أحبار طابعات', 'طباعة دعائية', 'مستلزمات جلسات'],
  242: ['تدريب برمجيات', 'دورات لغات', 'استضافة مواقع', 'تطوير مواقع'],
  244: ['موازين أرضية', 'موازين ديجيتال', 'كولات رقمية', 'معايرة موازين'],
  246: ['أنظمة إنذار', 'كاميرات مراقبة', 'إطفاء حريق', 'خدمات نظافة'],
  253: ['مفاتيح قواطع', 'لوحات توزيع', 'إنارة موفرة', 'أجهزة قياس'],
  273: ['أعمال ديكور', 'أبواب مصاعد', 'تشطيبات فندقية', 'مقاولات عامة'],
}

export const getProductNames = (sectorId) =>
  sectorProducts[sectorId] || ['منتج رئيسي', 'منتج ثانوي', 'خدمة متخصصة', 'حل متكامل']

export const sponsors = [
  { name: 'مكافحة الحرائق بافاريا', url: 'http://www.bavaria-firefighting.com', text: 'بافاريا' },
  { name: 'الأهرام للتجارة والصناعة', url: 'http://alahram-egy.com', text: 'الأهرام' },
  { name: 'الهيئة العربية للتصنيع', url: 'http://www.aoi.org.eg', text: 'الهيئة العربية للتصنيع' },
  { name: 'عبور لوجستيك', url: 'http://www.obourlogistics.com', text: 'عبور لوجستيك' },
  { name: 'معرض الشرق الأوسط للورق', url: 'https://www.papermideast.com/ksa/', text: 'Paper Middle East' },
  { name: 'مصر للمشروعات', url: 'http://www.egypt-projects.com', text: 'مصر للمشروعات' },
  { name: 'المعرض الدولي للعضلات وقوالب الضغط', url: 'http://www.misrcompressor.com', text: 'مصر كمبروسر' },
  { name: 'المعرض الدولي للطاقة والمياه', url: 'http://www.aquaenergyexpomea.com', text: 'Aqua Energy Expo' },
  { name: 'تكنولوجيا مصر', url: 'http://www.technologyegypt.com', text: 'تكنولوجيا مصر' },
  { name: 'معرض القاهرة للاستيراد', url: 'http://www.nilefairs.com', text: 'Nile Fairs' },
]

export const stats = {
  companies: 12480,
  factories: 5320,
  sectors: sectors.length,
  cities: cities.length,
}